apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-pusher
  labels:
    app: post-pusher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-pusher
  template:
    metadata:
      labels:
        app: post-pusher
    spec:
      containers:
      - name: post-pusher
        image: post_pusher:latest
        imagePullPolicy: IfNotPresent
        command: ["python", "main.py"]
        args: ["--kafka_host", "$(KAFKA_HOST)", "--multiple"]
        env:
        - name: KAFKA_HOST
          valueFrom:
            configMapKeyRef:
              name: post-pusher-config
              key: KAFKA_HOST
        resources:
          requests:
            memory: "256Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "100m"
